version: "3.9"

services:
  osjs:
    user: node
    build:
      context: .
    volumes:
      - .:/usr/src/osjs
    ports:
      - "${OSJS_NODE_PORT:-8000}:8000"
    environment:
      - NODE_ENV=production
      - NODE_PORT=${OSJS_NODE_PORT:-8000}
      - NODE_HOST=${OSJS_NODE_HOST:-localhost}
      - NODE_CONFIG=${OSJS_NODE_CONFIG:-config.json}
      - NODE_LOG=${OSJS_NODE_LOG:-osjs.log}
      - NODE_PID=${OSJS_NODE_PID:-osjs.pid}
      - NODE_USER=${OSJS_NODE_USER:-node}
      - NODE_GROUP=${OSJS_NODE_GROUP:-node}
